version: '3.9'


services:

  backend:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3000
    command: npm run dev

  db:
    image: postgres:latest  
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: katya@domain.com
        PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80 
    volumes:
      - pgadmin-data:/var/lib/pgadmin 

volumes:
  local_pgdata:
  pgadmin-data: